server:
  port: 8861
spring:
  application:
    name: order-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8855
      web-context-unify: false # 默认将调用链路收敛了
      datasource:
        flow-rule: #可以自定义
          nacos:
            server-addr: 127.0.0.1:8844
            username: nacos
            password: nacos
            dataId: order-sentinel-flow-rule
            rule-type: flow